### ISSUE TITLE
Project list search failure

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#1714]
Project list e.g. `shared with me` fails to gather projects when using search (see attached video). App falls to "Unable to  get the list of projects" and until I hit _Retry_ it will not change even when I search for something else.

@varmar05 can this be related to https://gitlab.cloud.lutraconsulting.co.uk/mergin/mergin/-/issues/794?

https://user-images.githubusercontent.com/22449698/137897190-d5858c10-03c7-4c29-9a77-e9981eb9672c.mp4

**Comment by jozef-budac** [comment]
This issue is also on "My projects" page and also for valid project names. 
When I try to search project "bug", which exists, I get this error. So basically search is not working. 
I would vote for this fix.

https://user-images.githubusercontent.com/83582181/168243242-08384bd7-ab08-45d6-bc47-cb9cc5fa3900.mp4
