### ISSUE TITLE
QT6: Problem opening a project

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2366]
I have problem with opening project tc06_data_providers
Project is not loaded or doesn't show map themes.
After opening this project, usually I can see map canvas from previous opened project

**Comment by wonder-sk** [comment]
bug caused by:
- a vector tile layer with JSON style
- when a rule has "text-size" with "stops"
- data-defined text size gets badly stored expression (as 0x01 character instead of the proper expression)

qgis version introduced: unclear

qgis version fixed: 3.20+, 3.18.?, 3.16.7

upstream fix: https://github.com/qgis/QGIS/pull/42456

**Comment by jozef-budac** [comment]
This was fixed by latest PRs
