### ISSUE TITLE
Mergin crashes when taking photos

### ISSUE THREAD

**Issue by qnmai** [MerginMaps/input#2666]
The app crashes when I take photos (about 1 out of 8 times). Upon taking the photo, no image preview is shown. Pressing back restarts the application.

This is what I'm using:
-SM-T575 tablet
-Mergin Maps 2.1

I don't have any active EXIF formulas (was originally testing this, and thought it was the culprit). It doesn't happen every time.

**Comment by qnmai** [comment]
Hi @tomasMizera -- we just switched tablets, so this is the first time i've noticed this happening. However, it may very well be this way for other projects...I will test an old project on this new tablet and get back to you. I've now shared the project. It's called [243923SIG_Adressage_Tumaraa]

**Comment by qnmai** [comment]
@tomasMizera I was able to reproduce the problem on a second project with this tablet.

**Comment by tomasMizera** [comment]
@erpas or @Tadeo98 can I ask you guys to follow with this one?

**Comment by Tadeo98** [comment]
Hello @qnmai ,
I am from Mergin Maps' support. 
I have access to the project, could you please let me know which layers containing the photo widget cause problems mentioned in your first message? I would like to replicate the issue first and to get it quick (the project consists of many layers), it would be helpful if you pointed me to particular layer and photo widget.
Thank you very much!

Kind regards,

Tadeas Cervik

**Comment by qnmai** [comment]
Hi @Tadeo98 It happens randomly with all or any of the layers and photo widgets... : /

I went back to version 1.6 and the problem does not seem to occur on this older version.

**Comment by qnmai** [comment]
update @Tadeo98 the problem persists even with 1.6, but less frequently.

**Comment by Tadeo98** [comment]
@qnmai thank you for your update

**Comment by Tadeo98** [comment]
Dear @qnmai ,
multiple attempts were conducted to replicate the issue but we are unable to do so.
Surely the app shouldn't crash with photos being taken but we also suspect that the camera application itself heavily contributes to this issue as it returns wrong data.
Simple (but a little annoying) workaround would be to upload the photos from gallery, not the camera app. So with every new feature, leave Mergin Maps app, take the photo and get back to the app and upload it from gallery.
Hopefully this gets fixed in future updates.
We are sorry for the inconvenience and grateful for your patience!

Kind regards

Tadeas Cervik

**Comment by qnmai** [comment]
Thanks for the feedback @Tadeo98

When my technician reported it, it took a while to reproduce (maybe about 45 entities added). It seemed like activating 3G made it worse. But it happens so randomly, that it's not easy to measure.
