### ISSUE TITLE
Enhancement - Allow GPS tracking

### ISSUE THREAD

**Issue by Brent-Edwards** [MerginMaps/input#500]
It would be really useful to allow GPS tracking from the device. This would be a separate "system" layer that one could activate to allow tracking through the device API.

GPX or XYZ/CSV would probably be the easiest to implement as they are easily read by OGR.

The file could be associated with the project and activated/deactivated with a separate button and the option to provide a name for the GPS track. Useful information to include in the file in addition to the XYZ coordinates would be GPS time, device time, hdop, pdop, vdop to evaluate accuracy. Including options for streaming time/accuracy filters would be useful as well.

**Comment by saberraz** [comment]
There are many ways of implementing this...but the least intrusive way IMO is:
First: having a global option to enable/disable tracking....default is set to disable
When enabled and user opens a project, the trail will be recorded in the background. In addition to the trail geometry, it would be good to add information: e.g. start date/time, end date/time, mergin username. End time can be when user closes the app completely (not if it is running in the background) or when user tries to sync data. 
The data can be saved per project (??) as a geopackage (???) and gets synced when user uploads the data through Mergin. Other users' trail can be appended to the same table.

**Comment by saberraz** [comment]
Suggestions are welcome for other methods of capturing trail.

**Comment by elanioazul** [comment]
Hi, probably its me I haven t dig enough in the app yet, but related to the functionality its is described in this conversation/issue, I tought setting a line layer to collect tracks as described in one of the tutorials would mean generate a GPX file. I realized this is not the case. On the contrary what happens is you paint a geometry line by conecting a string of vertexes. (I doubt now if each vertex entry you have to set a date/time when you preset a time/date field, or the date is only asked when editing the very first vertex).

This is super cool and handy but now I am wondering... Is there a way to get a GPX track file within Input app? With all the temporal controllers present in qgis3.14 and so on, I would find an important match to generete some sort of file in Input to "easily" connect with these temporal features. 

Maybe I am completelly wrong and there is already a way in Input trought you can collect time and altitude gps position synchronizely, in order to have a time continuos attribute to play around with temporal controller features. If this is the case, please point me out. 
Thx a lot guys

**Comment by saberraz** [comment]
https://twitter.com/lutraconsulting/status/1326435545183096832

**Comment by olliewearn** [comment]
Any update on this? Would be super useful to have GPS tracking.

**Comment by tomasMizera** [comment]
Hello @Brent-Edwards @olliewearn @elanioazul @KerszenP24
We currently gather requirements for the Tracking feature inside Mergin Maps Input.
We appreciate your comments and if you have some more requirements or details about your use case, please enter them into this form: https://forms.clickup.com/24429115/f/q9ghv-9204/DP4JBN8SXMF3HCQNLX Thank you!

**Comment by PeterPetrik** [comment]
implemented :)
